### ISSUE TITLE
Support integer vectors/matrices

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#19]
Currently everything is double

**Comment by coatless** [comment]
What is the hurt here with just assuming everything is `double`? Outside of storage concerns, I see more problems arising with overflows and common algebraic operations (`integer`/`integer` division).

Also,  the only integer structure possible would be `imat`/`ivec` (`int`) due to _R_'s mapping. So, the `umat`/`uvec` (`unsigned int`) wouldn't be accessed. (Perhaps with a specific type cast though?)
