### ISSUE TITLE
options to solve()

### ISSUE THREAD

**Issue by conradsnicta** [dirkschumacher/armacmp#29]
https://github.com/dirkschumacher/armacmp/blob/4cf86f8caff9ecb118754e4ec230e93c55cc6c1e/R/ast-classes.R#L464

Using [`solve_opts::fast`](http://arma.sourceforge.net/docs.html#solve) can provide considerable speedups here. 

For users mainly focused on speed, it might be useful to allow the specification of a fast solve directly from R code. Perhaps at the function level, or globally (eg. as an option for armacmp).

@coatless - thoughts?

**Comment by dirkschumacher** [comment]
I am wondering what the best way forward is for `arma` specifc parameters. Maybe a general convetion to add it at the function level with namespaced parameters? E.g. `sum(X, arma_solve_opts = c("fast", "opt2", "opt3"))`.

But then that produces invalid R code ... so not sure.

Global options would be another solution, but then you would set these flags for all `solve` operations in your code.

**Comment by coatless** [comment]
I think a global option would be needed instead of localized variants. Consider the `plugin` feature of `Rcpp` for triggering this kind of option.

I say this because the goal should be to ensure the **written** _R_ code is as close to the original as possible. Anything higher will likely cause a decrease in engagement as this package really serves to bring new people into the world of _C++_ while simultaneously allowing experts a speedier translation.

**Comment by conradsnicta** [comment]
This has been resolved upstream in Armadillo 9.800 ([link](http://arma.sourceforge.net/download.html)). The `solve()` function no longer applies iterative refinement by default, leading to massive speedups.

**Comment by dirkschumacher** [comment]
Oh nice!
